UserService/Controller
kir-dev/collage-schedule-planner pull request #15
Opened 2024-05-25 17:42 UTC by GSzabi11

Szerintem megvan, nekem müködik minden

2024-05-27 04:16 UTC, balintking requested changes
You're implementation is correct, I only requested a few changes👔

2024-05-27 04:16 UTC, balintking commented on package-lock.json
Please delete this file, because it was added by npm, but in this project we use yarn instead

2024-05-27 04:16 UTC, balintking commented on apps/backend/src/user/dto/create-user.dto.ts
Please delete the dto and entity files, too, because now we focus on only the endpoints. the validation will be the next step. And we'll work on new branches on that.

2024-05-27 04:16 UTC, balintking commented on apps/backend/src/user/user.controller.spec.ts
Also, do not need the spec.ts files, these are for testing what we are not going to do right now

2024-05-27 04:16 UTC, balintking commented on package.json
> +  },
Don't need dependencies here, prisma is in the backend app

2024-05-27 04:16 UTC, balintking commented on package.json
> +    "@types/jest": "^29.5.12",
Don't need that also

2024-05-27 04:16 UTC, balintking commented on apps/backend/package.json
> +    "@nestjs/testing": "^10.3.8",
We don't test

2024-05-27 04:16 UTC, balintking commented on apps/backend/src/user/user.service.ts
> +    const user = await this.prisma.user.findUnique({ where: { id } });
Use try-catch in all of these methods

2024-06-04 11:59 UTC, csiszaralex approved these changes
Nice work! 🥇

2024-06-04 17:20 UTC, merged