Feature/User validation
kir-dev/collage-schedule-planner pull request #20
Opened 2024-05-28 17:14 UTC by GSzabi11

2024-06-04 17:45 UTC, csiszaralex requested changes
You have the same problems like #19 please check it and resolve the problems

2024-06-04 17:45 UTC, csiszaralex commented on package.json
> +
Why are you added new lines?

2024-08-28 23:52 UTC, balintking requested changes
Sorry for the little late, please resolve these few things quickly and we can close this issue

2024-08-28 23:52 UTC, balintking commented on apps/backend/src/user/entities/user.entity.ts
> +  groups: number;
We don't need the groups and events list fields. They only exist in prisma's interpretation of the database, but they are not real.

2024-08-28 23:52 UTC, balintking commented on apps/backend/src/user/dto/create-user.dto.ts
> +export class CreateUserDto extends OmitType(User, ['id', 'events', 'groups']) {}
So we won't need them here either

2024-09-18 13:57 UTC, balintking approved these changes

2024-09-18 17:50 UTC, csiszaralex approved these changes
Nice work!

2024-09-18 18:12 UTC, merged